### ISSUE TITLE
Add more scalars here

### ISSUE THREAD

**Issue by arokem** [yeatmanlab/pyAFQ#505] opened 2020-10-05 22:29 UTC
https://github.com/yeatmanlab/pyAFQ/blob/a7ed62787a703a2ffde0d5c10f66baf2f0abcd2c/AFQ/api.py#L815

We should make it possible (though maybe not the default to calculate more scalars): 

DTI: AD, RD

DKI: MK, RK, ... 

WMTI model (derived from DKI): https://dipy.org/documentation/1.2.0./examples_built/reconst_dki_micro/#example-reconst-dki-micro

MAPMRI: https://dipy.org/documentation/1.2.0./examples_built/reconst_mapmri

And others

**Comment by 36000** [comment] 2020-10-05 22:46
This is related to / may be a duplicate of: #368

**Comment by arokem** [comment] 2020-10-15 20:17
Furthermore, just like tractography, it would be good to allow adding scalars as BIDS filters. The challenge would be that we might have more than one scalar to add, which we would need to consider in the API.

**Comment by 36000** [comment] 2021-08-05 17:21
#733 added AD, RD, MK, RK. Custom scalars from BIDS filters also already added.

**Closed** 2022-05-24 21:42 UTC
Labels: enhancement
